"""Add user profile fields

Revision ID: 6dcd25067129
Revises: 
Create Date: 2026-02-26 22:49:16.945587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dcd25067129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='日程ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='日程标题',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='日程描述',
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=mysql.ENUM('high', 'medium', 'low', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='优先级',
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'in_progress', 'completed', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_start_time'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_table_comment(
        existing_comment='日程表'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='密码（加密）',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_username'))
        batch_op.drop_table_comment(
        existing_comment='用户表'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='密码（加密）',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('theme')
        batch_op.drop_column('language')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_table_comment(
        '日程表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_start_time'), ['start_time'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'in_progress', 'completed', collation='utf8mb4_unicode_ci'),
               comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('priority',
               existing_type=mysql.ENUM('high', 'medium', 'low', collation='utf8mb4_unicode_ci'),
               comment='优先级',
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment='结束时间',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment='开始时间',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='日程描述',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='日程标题',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='日程ID',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
